apiVersion: apps/v1 
kind: Deployment
metadata:
  name: demo-api
spec: 
  selector:
    matchLabels:
      app: demo-api
  replicas: 2 # tells deployment to run 1 pod matching the template
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
      - name: demo-api-containers
        image: gcr.io/roidtc-oct-user616/internal-image:v1.0.0
        env: 
        - name: PORT
          value: "8082"
        - name: GOOGLE_CLOUD_PROJECT
          value: "roidtc-oct-user616"
        ports:
        - containerPort: 8082
            
        
